title: Fractal
baseurl: /
permalink: '/:title/'
palette: blue
palettes:
  blue:
    sass:
      color: '#4696e5'
  magenta:
    sass:
      color: '#db5c7a'
  purple:
    sass:
      color: '#786dc2'
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: '/posts/:title/'
